-- =========================================================
-- 036_error_recovery_and_legacy_cleanup.sql
--
-- Fixes two problems exposed by the first real orchestrator run:
--
-- 1. 'error' was terminal with no outgoing edges. A transient failure
--    (Ollama not running, network blip) permanently killed an application.
--    Terminal should mean "the pipeline is genuinely done with this", not
--    "a dependency was briefly unavailable".
--
-- 2. Documents generated before migration 034 carry qa_status='pending_review'
--    and no evidence_map.claims. They cannot be verified, because there are no
--    recorded claims to check against their sources. They are marked failed
--    rather than quietly passed.
-- =========================================================

BEGIN;

-- ---------------------------------------------------------
-- 1. 'error' becomes recoverable
-- ---------------------------------------------------------

UPDATE pipeline_steps
SET is_terminal = false,
    requires_human = true,
    description = 'Halted on an error. Recoverable once the cause is fixed.'
WHERE step = 'error';

-- Edges back out of error, one per step that can enter it.
INSERT INTO pipeline_transitions (from_step, to_step, automated, note)
VALUES
  ('error', 'intake',         false, 'Retry from the beginning.'),
  ('error', 'screened',       false, 'Dependency restored; retry fit analysis.'),
  ('error', 'fit_analyzed',   false, 'Dependency restored; retry generation.'),
  ('error', 'docs_generated', false, 'Dependency restored; retry verification.'),
  ('error', 'abandoned',      false, 'Give up on this application.')
ON CONFLICT (from_step, to_step) DO UPDATE
SET automated = EXCLUDED.automated, note = EXCLUDED.note;

-- Also let a failed-QA application be regenerated by the orchestrator once
-- the user has fixed the underlying assets. Previously this required manual
-- SQL, which is a bad place to put a routine recovery path.
INSERT INTO pipeline_transitions (from_step, to_step, automated, note)
VALUES ('docs_failed_qa', 'fit_analyzed', false,
        'User addressed the grounding gap; regenerate documents.')
ON CONFLICT (from_step, to_step) DO UPDATE
SET automated = EXCLUDED.automated, note = EXCLUDED.note;

-- ---------------------------------------------------------
-- 2. Retry bookkeeping, so repeated transient failures are visible
-- ---------------------------------------------------------

ALTER TABLE applications
  ADD COLUMN IF NOT EXISTS error_count      int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_error_step  text,
  ADD COLUMN IF NOT EXISTS last_error_at    timestamptz;

-- ---------------------------------------------------------
-- 3. Legacy documents that predate the evidence_map contract
-- ---------------------------------------------------------

UPDATE generated_documents
SET qa_status = 'fail',
    qa_report = jsonb_build_object(
      'verifier_version', 'n/a',
      'error', 'Generated before evidence_map existed. No recorded claims, '
               || 'so no verification is possible. Regenerate with L6.',
      'legacy_qa_status', qa_status
    ),
    qa_checked_at = now()
WHERE qa_status IS NOT NULL
  AND qa_status NOT IN ('pass', 'revise', 'fail')
  AND NOT (evidence_map ? 'claims');

-- Any other non-standard qa_status with claims present goes back to the queue.
UPDATE generated_documents
SET qa_status = NULL
WHERE qa_status IS NOT NULL
  AND qa_status NOT IN ('pass', 'revise', 'fail')
  AND (evidence_map ? 'claims');

-- ---------------------------------------------------------
-- 4. Operator view: what is stuck and why
-- ---------------------------------------------------------

CREATE OR REPLACE VIEW v_applications_stuck AS
SELECT
  a.id AS application_id,
  a.company,
  a.job_title,
  a.current_step,
  a.error_count,
  a.last_error_step,
  a.last_error_at,
  (SELECT e.reason FROM pipeline_events e
    WHERE e.application_id = a.id
    ORDER BY e.created_at DESC LIMIT 1) AS last_event_reason
FROM applications a
JOIN pipeline_steps ps ON ps.step = a.current_step
WHERE ps.requires_human = true
  AND ps.is_terminal = false
ORDER BY a.last_error_at DESC NULLS LAST, a.updated_at DESC;

COMMENT ON VIEW v_applications_stuck IS
  'Applications waiting on a human: approvals, failed QA, and errors.';

COMMIT;
