-- 083_v1_generalized_ats_registry.sql
-- V1.0 generalized ATS identity/capability seed.
BEGIN;

ALTER TABLE ats_companies
  ADD COLUMN IF NOT EXISTS source_url text;

COMMENT ON COLUMN ats_companies.source_url IS
  'Official company careers/job URL for structured-web discovery when no stable native public API is configured.';

ALTER TABLE ats_capabilities DROP CONSTRAINT IF EXISTS ats_capabilities_autofill_mode_check;
ALTER TABLE ats_capabilities ADD CONSTRAINT ats_capabilities_autofill_mode_check
  CHECK (autofill_mode IN ('review_only', 'single_page', 'multi_page', 'generic_browser'));

INSERT INTO ats_capabilities
  (ats_type, supports_discovery, supports_static_text, supports_radio, supports_select,
   supports_upload, supports_multi_page, autofill_mode, notes)
VALUES
  ('greenhouse', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('lever', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ashby', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('smartrecruiters', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('recruitee', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('workable', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('breezy', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=native_api. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('workday', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('icims', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jibe_icims', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('oracle_taleo', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('oracle_hcm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('oracle_peoplesoft_candidate_gateway', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('oracle_selectminds', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('successfactors', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('successfactors_legacy_rcm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('successfactors_rmk', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobvite', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('adp_workforcenow', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ukg', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('dayforce', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('bamboohr', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jazzhr', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('clearcompany', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('teamtailor', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('pinpoint', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('rippling', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('paycom', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('paylocity', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('paycor', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('paychex', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('isolved', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('personio', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('zoho_recruit', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('freshteam', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('manatal', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('loxo', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('recruiterflow', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('recruitcrm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobadder', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('bullhorn', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('avionte', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ceipal', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobdiva', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('crelate', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('pcrecruiter', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('trackerrms', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('vincere', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('tempworks', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('akkencloud', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('smartsearch', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('avature', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('eightfold', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('phenom', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('beamery', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('gem', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('paradox_olivia', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('clinch_career_pages', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('radancy_talentbrew', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('talemetry', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('findly_cws', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('getro', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('join', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('softgarden', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('factorial', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('polymer', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('deel', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('cornerstone_csod', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ibm_kenexa_brassring', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('infor_cloudsuite_hcm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('peoplefluent', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('pageup', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('silkroad', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('deltek', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('arcoro', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('healthcaresource_symplr', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('frontline_applitrack', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('powerschool_talented_peopleadmin_schoolspring', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('neogov', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobaps', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('calcareers', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('statejobsny', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('usajobs', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('usps_applytohire', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('nyc_teacher_support_network', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('winocular', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('applicantpro', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('applicantstack', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('applicantpool', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('hiringthing', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobscore', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('hirebridge', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('trakstar_hire', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('exacthire', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('eddy', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('wizehire', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('cats', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('gohire', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('homerun', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('occupop', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('careerspage', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('applicantai', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('careerpuck', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('hrm_direct', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('peopleforce', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('talentlyft', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('talexio', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('sagehr', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('careerplug', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('hireology', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('fountain', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('workstream', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('harri', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('homebase', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('talentreef', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('apploi', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('oleeo', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('yello', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('comeet', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('dover', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('onehundredhires', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ismartrecruit', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobsoid', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('recooty', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('targetrecruit', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('firefish', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('happlicant', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('recruitbpm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('laboredge', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('brightmove', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('corecruit', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('supportfinity', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('keka', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('hireez', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('recruiterpm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('top_echelon', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('scout_talent', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('jobylon', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('tenstreet', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('acquiretm', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('talentnest', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('the_applicant_manager', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('hiretouch', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('newton_software', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ultrastaff_edge', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('mystaffingpro', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('balancetrak', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('ats_on_demand', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('nowhire', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('vikus', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('virtus', true, true, true, true, true, true, 'generic_browser', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('appcast_wordpress_jobs', true, false, false, false, false, false, 'review_only', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('attrax_cityjobs', true, false, false, false, false, false, 'review_only', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('directemployers_jobs', true, false, false, false, false, false, 'review_only', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('nlx_google_talent', true, false, false, false, false, false, 'review_only', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.'),
  ('custom', true, true, true, true, true, true, 'multi_page', 'Registry-driven generic browser support; strategy=structured_web. Writes remain page-bound, approval-bound, and safe-pause on unknown controls.')
ON CONFLICT (ats_type) DO UPDATE SET
  supports_discovery=EXCLUDED.supports_discovery,
  supports_static_text=EXCLUDED.supports_static_text,
  supports_radio=EXCLUDED.supports_radio,
  supports_select=EXCLUDED.supports_select,
  supports_upload=EXCLUDED.supports_upload,
  supports_multi_page=EXCLUDED.supports_multi_page,
  autofill_mode=EXCLUDED.autofill_mode,
  notes=EXCLUDED.notes,
  updated_at=now();

INSERT INTO allowed_domains (domain, category, notes, enabled)
VALUES
  ('applicantpool.com', 'ats', 'ATS registry: ApplicantPool', true),
  ('applicantpro.com', 'ats', 'ATS registry: ApplicantPro', true),
  ('applicantstack.com', 'ats', 'ATS registry: ApplicantStack', true),
  ('applitrack.com', 'ats', 'ATS registry: Frontline Education / AppliTrack', true),
  ('applytojob.com', 'ats', 'ATS registry: JazzHR / ApplyToJob', true),
  ('ashbyhq.com', 'ats', 'ATS registry: Ashby', true),
  ('avature.net', 'ats', 'ATS registry: Avature', true),
  ('bamboohr.com', 'ats', 'ATS registry: BambooHR Hiring', true),
  ('brassring.com', 'ats', 'ATS registry: IBM Kenexa BrassRing', true),
  ('breezy.hr', 'ats', 'ATS registry: Breezy HR', true),
  ('bullhornstaffing.com', 'ats', 'ATS registry: Bullhorn', true),
  ('calcareers.ca.gov', 'government', 'ATS registry: CalCareers', true),
  ('career-pages.com', 'ats', 'ATS registry: Clinch / career-pages.com', true),
  ('careers-page.com', 'ats', 'ATS registry: CareersPage', true),
  ('catsone.com', 'ats', 'ATS registry: CATS Applicant Tracking', true),
  ('csod.com', 'ats', 'ATS registry: Cornerstone OnDemand / CSOD', true),
  ('dayforcehcm.com', 'ats', 'ATS registry: Dayforce Recruiting', true),
  ('eightfold.ai', 'ats', 'ATS registry: Eightfold AI', true),
  ('exacthire.com', 'ats', 'ATS registry: ExactHire', true),
  ('factorialhr.com', 'ats', 'ATS registry: Factorial HR', true),
  ('freshteam.com', 'ats', 'ATS registry: Freshteam', true),
  ('governmentjobs.com', 'ats', 'ATS registry: NEOGOV / GovernmentJobs', true),
  ('greenhouse.io', 'ats', 'ATS registry: Greenhouse', true),
  ('hirebridge.com', 'ats', 'ATS registry: Hirebridge', true),
  ('hiringthing.com', 'ats', 'ATS registry: HiringThing', true),
  ('icims.com', 'ats', 'ATS registry: iCIMS', true),
  ('jibeapply.com', 'ats', 'ATS registry: Jibe / iCIMS Candidate Experience', true),
  ('jobadder.com', 'ats', 'ATS registry: JobAdder', true),
  ('jobapscloud.com', 'ats', 'ATS registry: JobAps', true),
  ('jobs2web.com', 'ats', 'ATS registry: SAP SuccessFactors RMK / Career Site Builder', true),
  ('jobscore.com', 'ats', 'ATS registry: JobScore', true),
  ('jobvite.com', 'ats', 'ATS registry: Jobvite', true),
  ('join.com', 'ats', 'ATS registry: JOIN', true),
  ('lever.co', 'ats', 'ATS registry: Lever', true),
  ('myjobs.adp.com', 'ats', 'ATS registry: ADP Workforce Now Recruiting', true),
  ('myworkdayjobs.com', 'ats', 'ATS registry: Workday Recruiting', true),
  ('oraclecloud.com', 'ats', 'ATS registry: Oracle Recruiting Cloud / Fusion HCM', true),
  ('pageuppeople.com', 'ats', 'ATS registry: PageUp', true),
  ('paycomonline.net', 'ats', 'ATS registry: Paycom ATS', true),
  ('peopleforce.io', 'ats', 'ATS registry: PeopleForce', true),
  ('pinpointhq.com', 'ats', 'ATS registry: Pinpoint', true),
  ('recruitee.com', 'ats', 'ATS registry: Recruitee', true),
  ('recruiterbox.com', 'ats', 'ATS registry: Trakstar Hire / Recruiterbox', true),
  ('recruiterflow.com', 'ats', 'ATS registry: Recruiterflow', true),
  ('recruiting.paylocity.com', 'ats', 'ATS registry: Paylocity Recruiting', true),
  ('smartrecruiters.com', 'ats', 'ATS registry: SmartRecruiters', true),
  ('softgarden.io', 'ats', 'ATS registry: Softgarden', true),
  ('statejobs.ny.gov', 'government', 'ATS registry: StateJobsNY', true),
  ('successfactors.com', 'ats', 'ATS registry: SAP SuccessFactors Recruiting', true),
  ('talentlyft.com', 'ats', 'ATS registry: TalentLyft', true),
  ('taleo.net', 'ats', 'ATS registry: Oracle Taleo Enterprise', true),
  ('teamtailor.com', 'ats', 'ATS registry: Teamtailor', true),
  ('ukg.net', 'ats', 'ATS registry: UKG Pro Recruiting / Ultimate', true),
  ('ultipro.com', 'ats', 'ATS registry: UKG Pro Recruiting / Ultimate', true),
  ('usajobs.gov', 'government', 'ATS registry: USAJOBS / USA Staffing', true),
  ('workable.com', 'ats', 'ATS registry: Workable', true),
  ('workforcenow.adp.com', 'ats', 'ATS registry: ADP Workforce Now Recruiting', true),
  ('zohorecruit.com', 'ats', 'ATS registry: Zoho Recruit', true)
ON CONFLICT (domain) DO UPDATE SET
  category=EXCLUDED.category,
  notes=EXCLUDED.notes,
  enabled=true;

INSERT INTO component_registry
  (name, component_type, layer, purpose, trainable, status, notes, created_at, updated_at)
VALUES
  ('ats_registry_v1', 'service', 'L0',
   'Canonical ATS identity, aliases, URL/signature detection and capability metadata.',
   false, 'active',
   'Broad US-facing catalog plus custom fallback; browser behavior remains centralized and approval/page/domain bound.',
   now(), now()),
  ('ats_structured_web_discovery_v1', 'service', 'L0',
   'Generic schema.org JobPosting discovery from explicitly configured official career pages.',
   false, 'active',
   'Fallback for vendors without stable native public list APIs; never invents private vendor endpoints.',
   now(), now())
ON CONFLICT (name) DO UPDATE SET
  purpose=EXCLUDED.purpose, status=EXCLUDED.status, notes=EXCLUDED.notes, updated_at=now();

COMMIT;
